/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lox;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;


public class Lox {
    public String getGreeting() {
        return "Usage: lox [script]";
    }

    public static void main(String[] args) throws IOException {
        Lox lox = new Lox();
        System.out.println("llooooooxxxxx");
        System.out.println(lox.getGreeting());
    }
}

